#!/bin/bash
instance_name=$1
region="us-west-1"
expiration_date=`date -v+14d "+%Y-%m-%dT00:00:00"`
service_role="service-role/AmazonEC2RunCommandRoleForManagedInstances"



# Check if argument is passed
if [ -z "$instance_name" ]; then
    >&2 echo "Missing required instance-name argument. Usage: $0 instance-name (e.g. $0 google-cloud-01)"
    exit 1
fi



aws ssm create-activation \
    --description "Generated by $(id -un) on $(date) for $instance_name" \
    --iam-role $service_role \
    --default-instance-name "$instance_name" \
    --registration-limit 1 \
    --region "$region" \
    --expiration-date "$expiration_date"
